#! /usr/bin/python

import curses
import traceback

import drain



def main(stdscr):
    app = drain.App("GalaxieDrake_mo", stdscr)
    app.run()

if __name__ == '__main__':
    try:
        curses.wrapper(main)
    except:
        traceback.print_exc()

